### ISSUE TITLE
False positive - Cloudwatch log metric pattern is invalid

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/opa_checks#33]
Currently failing in the notification-terraform repo.

```
pattern        = "{ $.delivery.providerResponse = \"Blocked as spam by phone carrier\" }"
```

Log: https://github.com/cds-snc/notification-terraform/runs/5586297935?check_suite_focus=true#step:8:444

**Comment by maxneuvians** [comment]
Fixed in main branch
